### ISSUE TITLE
G1000 seemingly completely non-functional in the latest MSFS update

### ISSUE THREAD

**Issue by fsendventd** [Working-Title-MSFS-Mods/fspackages#1206]
Basically what it says on the tin. SU4, G1000 v0.3.7. The PFD doesn't show any engine information when the MFD is turned off. None of the instruments on either the PFD or MFD work, for that matter. They stay "frozen" at the values they were at when turned on, and don't change at all as the aircraft changes speed, altitude, or direction. Same goes for the engine instruments. I've also been having some issues with the DA62X and DA40-NGX mods, and I think this might be what's causing it. Any idea what I can do to fix this? I've tried reinstalling the mod.

**Comment by ArashHosseini** [comment]
Same here, while Vatsim or Ivao client is running, PFD and MFD became frozen. Its seems to be some signal stream which blocks the PFD.

**Comment by Baldk9** [comment]
I'm glad I'm not the only one. Total non functional aircraft since update.

**Comment by mattnischan** [comment]
Can you all double check that you have installed the latest mod version? The freezes for SU4 were fixed in 0.3.7.

You may also want to try with only the G1000 0.3.7 mod installed and nothing else, and see if another mod is causing a conflict. We cannot reproduce any PFD or MFD freezes now on the latest.

**Comment by MARCELOHIDALGOMARTINS** [comment]
Hello.
For the G1000 worktitle to work here, exclude three "mods" z-bonanza-g36-improvement, worktitle-gx and worktitle - aircraft-cj4. One of them was locking the GlassCockpit buttons.

**Comment by Baldk9** [comment]
I did the recommended changes, but still non-functioning. I then reinstall the latest update and still not working, all this happened after the last MSFS update.

**Comment by fsendventd** [comment]
It looks like the current version of the GX mod is what's causing the issues, removed that one and all is fine. That's fair, I suppose, considering that mod is still in development.

**Comment by ArashHosseini** [comment]
@fsendventd deleting the GX mod did it, thx.

**Comment by mattnischan** [comment]
And that was with the latest G3X dev8 version?

**Comment by ArashHosseini** [comment]
@mattnischan yes, G3X **dev8**.

**Comment by Baldk9** [comment]
G3x is located where? Sent from Mail for Windows 10 From: S. Arash HosseiniSent: Friday, May 28, 2021 12:15To: Working-Title-MSFS-Mods/fspackagesCc: Baldk9; CommentSubject: Re: [Working-Title-MSFS-Mods/fspackages] G1000 seemingly completely non-functional in the latest MSFS update ***@***.*** yes, G3X dev8.—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by fsendventd** [comment]
> 
> 
> And that was with the latest G3X dev8 version?

G3X dev8, yes.

**Comment by kherner** [comment]
Hello,

I had the same problem, and removing the g3x package solved it. I also tried rolling the g3x back to dev7 just to see what would happen, and the issue was also present.

**Comment by Richard-Walter** [comment]
I had the same issue but i had  g3x back to dev5
