### ISSUE TITLE
CJ4: Aircraft Moving off When Parke Brake is released (without the engines running)

### ISSUE THREAD

**Issue by TicTockRock** [Working-Title-MSFS-Mods/fspackages#222]
Hi

Thank you for this MOD its great, the work you guy’s have done is truly fantastic.

I have an issue with the latest version, where if I release the parking brake without having the engines running the aircraft takes off across the ground gathering speed as it goes (I crashed into a terminal 😀 my first crash, so crash damage works) . I then tried the same thing with the engines running and it did not do it this time. Not a major problem, as I can obviously just get the engines running before releasing park brake and getting a pushback.

I did remove all MODS from the community folder and test it again and the problem was still there.

Just thought I would raise it, in case anybody else notices the same.

**Comment by dga711** [comment]
Thank you for the report and good find!

Since we implemented a custom thrust model it is possible it slipped through to not output any thrust when engines off :-)
Guess we will fix this one pretty quick.

**Comment by mattnischan** [comment]
@TicTockRock,

That does definitely sound like an Asobo bug, especially since it still appears with no mods installed. Unfortunately, we don't have control of the engine thrust from aircraft code (other than engines.cfg adjustments), so it would not be possible for us to tackle this kind of issue.

But we definitely appreciate you flying the mod and thank you a bunch for your report!

**Comment by TicTockRock** [comment]
Hi Mattnischan

Thank you for taking the time to read this issue.

Maybe I should have been more explicit in my original post and it should have read "all other MODS". For me this only happens with the latest release for the CJ4 MOD. If I remove the CJ4 MOD and load the stock ASBO CJ4 this does not happen!! I put the CJ4 MOD back in and in starts again.

I assume you have not been able to replicate this, so its something peculiar to my system I guess.

Anyways thanks again for taking the time to look.

**Comment by mattnischan** [comment]
Ah, yeah, I definitely misunderstood!

I'll reopen this and see if any of us can replicate it.

**Comment by K20017** [comment]
I just checked it, when you turn the engines off, somehow the thrust jumps to 1800lbs per engine.  Really weird, will look at it now.
