### ISSUE TITLE
Plane looking to lift off again upon landing

### ISSUE THREAD

**Issue by rbywater** [Working-Title-MSFS-Mods/fspackages#865]
Flying into NZWN on ILS 16 approach, disabled AP & YD about 500 feet, full flaps and followed glidescope fairly closely. Idled throttle over threshold and touched down and released stick and plane started to lift off again. Again pushed stick forward to touchdown again and released upon which it started to lift off again. Had to keep stick pushed forward while retracting all flaps before I could release stick although not sure if it was the flaps or the fact that the speed had bled off by then that meant it no longer took to the skies again.

**Comment by dga711** [comment]
Should be fixed in 0.10.1

**Comment by darkshine2311** [comment]
Hello,

Was the problem fixed ? I still have the same problem with 10.0.1 

Thank you so much for your great work on this aircraft !!

Have a nice day.

**Comment by mattnischan** [comment]
@darkshine2311 As in the real CJ4, proper procedure is to engage the speedbrakes to full, which will angage the ground spoilers and should get the nose down much more quickly as it breaks the wing lift.

In addition make sure you are landing with the proper V speeds.

**Comment by darkshine2311** [comment]
Hello, I was right at the vspeeds, and spoiler were fully deployed (I have a special axis for that to be quick), loading of passengers and cargo was also done.

The flare is really not a problem, the runway touch is perfect, only on the ground the aircraft seems to weight 200 gramms :-D 

Some on the discord group have also say that they were able to climb with speedbrake deployed.

Thank you !
